print ("== Advenure Simulator ⚔️ ==")
print (" ")
print ("Welcome to your adventure 📜")
print ("I am going to ask you a bunch of questions and then create an epic story with you as the star! 🤩")
print (" ")
name = input ("What's your rockstar name?🧑🏾‍🎤:  ")
enemy_name = input ("What's your Nemesis name?😈:  ")
superpower = input ("What's your cool superpower?💪🏾:  ")
location = input ("Where is your super secret Headquaters?🌋:  ")
food = input ("What's your favorite power-meal?🍴:  ")
print (" ")
print ("Hello", name+"! Your ability will make sure you never have to look at", enemy_name, "ever again. You eat", food, "as you leave", location, "to use your incredible", superpower, "to fight", enemy_name, "one last time.")